name: photolog
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:

  cupertino_icons: ^1.0.2

  device_info_plus: ^8.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  hooks_riverpod: ^2.1.1
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.7.0
  uuid: ^3.0.7

dev_dependencies:

  build_runner: ^2.3.2
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4

flutter:

  uses-material-design: true
