name: photolog
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:

  cloud_firestore: ^4.4.3

  cupertino_icons: ^1.0.2

  device_info_plus: ^8.0.0

  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14

  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16

  flutter_riverpod: ^2.3.0

  flutter_slidable: ^2.0.0

  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.5
  hooks_riverpod: ^2.1.1
  http: ^0.13.5

  image_picker: ^0.8.5

  intl: ^0.17.0
  json_annotation: ^4.7.0
  table_calendar: ^3.0.8
  uuid: ^3.0.7

dev_dependencies:

  build_runner: ^2.3.2
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  image: "assets/images/target.png"
  color: "ffffff"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"
